server:
  port: 4444

spring:  application:    name: Zuul-Proxy-Server

eureka:  client: #   eureka-server-port: 2222
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:2222/eureka/
  instance:
    hostname: localhost


zuul:
  prefix: /api  routes:    calldetail-service:
      service-id: CALLDETAIL-SERVICE
      path: /calldetail-service/**
      strip-prefix: false
    friendfamily-service:
      service-id: FRIENDFAMILIY-SERVICE
      path: /friendfamily-service/**
      strip-prefix: false
    customer-service:
      service-id: CUSTOMER-SERVICE
      path: /customer-service/**
      strip-prefix: false    
    plan-service:
      service-id: PLAN-SERVICE
      path: /plan-service/**
      strip-prefix: false  