eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:2222/eureka/
  instance:
    hostname: localhost

server:
  port: 8400

spring:
  application:
    name: CALLDETAIL-SERVICE
  datasource:
    username: root
    password: piyush
    url:  jdbc:mysql://localhost:3306/infytel-calldetails?useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true      
# create-drop create update

# below comes under sprin.sleuth
  sleuth:
    enabled: true
    sampler:
      rate: 1
  zipkin:
    enabled: true
    base-url: http://localhost:9411 
    #http://${tracking-host:tracking}:9411 

management:
  endpoints:
    web:
      exposure:
        include:
        - "*"