eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:2222/eureka/
  instance:
    hostname: localhost

server:
  port: 8600

spring:
  application:
    name: FRIENDFAMILIY-SERVICE
  datasource:
    username: root
    password: piyush
    url:  jdbc:mysql://localhost:3306/infytel-friend-family?useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true      
# create-drop create update


management:
  endpoints:
    web:
      exposure:
        include:
        - "*"         